# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("binomial_1par", "binomial_2par", "normal", "ordered_multinomial", "poisson", "predict_delta_new", "survival_mspline", "survival_param")

# load each stan module
Rcpp::loadModule("stan_fit4binomial_1par_mod", what = TRUE)
Rcpp::loadModule("stan_fit4binomial_2par_mod", what = TRUE)
Rcpp::loadModule("stan_fit4normal_mod", what = TRUE)
Rcpp::loadModule("stan_fit4ordered_multinomial_mod", what = TRUE)
Rcpp::loadModule("stan_fit4poisson_mod", what = TRUE)
Rcpp::loadModule("stan_fit4predict_delta_new_mod", what = TRUE)
Rcpp::loadModule("stan_fit4survival_mspline_mod", what = TRUE)
Rcpp::loadModule("stan_fit4survival_param_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("rstantools_model_", model_name)))
})
